# Generated by Django 4.2 on 2023-07-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comercio', '0005_cliente_imagen_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouse',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
